
server:
  port: 30001
eureka:
  client:
    # 表示是否注册自身到eureka服务器  
    register-with-eureka: true
    # 是否从eureka上获取注册信息  
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:20002/eureka/
spring:
  application:
    name: client1




feign:
  okhttp:
    enabled: true
  hystrix:
    enabled: true