alipay:
  appid: 2016101600697642
  gateway: https://openapi.alipaydev.com/gateway.do
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAn+e4XvV7jki+qTsL9YcoVQIVkopK9vmyJRuMhKFAsb0Y0Ta+Ioy2bzFU6Gh+T/w6/r3vLbKhmCex/Y+K1H1+p86uaO1iA3rszNeM9Ezpq4qKWJDwGZ1QOxRhBAazWE3SVe25CertVEddLFkATBtuZMPWMh5dmwHnHG49YSCcmPSENIhaGRYj3bDXXHfIjlgUEsvB/z2DgjzY7JrbA2S62LRwPTIxhhkT8F92IEq1BD5gMsswAA2ipPQhCio9Q0Jw4QO9+bpIm7gQ5FgDLCSAjRBYfJdSpD6oLCRz1qfeg3OLOdYCQpOb/TsPbU8AbbIrrYg4z4wvzKC0LC+XBJmvawIDAQAB
  privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDtZsQ4i1TW1y+me/fOpiwUO0ivn2efqY3eT9EvMWeilM/AsFekKG68cTeT+FpXdi3XYxaPIcRSU1wCxOAAeEFTTNzrNfbtr+9OPz5xRicYXsuhHiNUBv6QKv7fFEdMJ0AruI48Lksio8RQ5gggED2WkavC4uj1Jtm/6gjsgxPG/xLMe4xaeYPEpqc9pcKJLiw0m7l2h5fwZUsQxdZ376MO6ngXelNjrE0fjieezgSVvUMlTnvM9LJTBQeWzu0UtLTQIhbQrLVtpKWQfdHSYSovACEJ+2kH7gzuSeA89swSVNkdNk7mjF1Ka7971pY5MFajSHZO3lWAxRssPyYzyRyxAgMBAAECggEAHRlImemyJ3dO1uhBEqpZos01dpliWTauNf6wlElI+6uj32l+BJgUIrL57gA2CpxouArkO/0WlES1dX1uO4CB+VTli0sdDjtPaNblr3q61gjgison6GfHEiLDBNL2fkYdXn6LqKLAAOnz6TqY6l0zP15xoDyx80Kk1Bo6p8rVRMHIueZRN0GEyyIW1rMlHMXVb+VGz9iSLWQypg8aLm34hvJjVKzBnn2u14dD57HlDBaHwDG5/jtGUVuGcyq+VrNX93YKWU5cGM2D+aciUIe70/NE0g1dRHx2kGPt+6xx86AUDDoEydVixqsP8pVQ902D/nd6SGqpBejhwcK2k+FO9QKBgQD6UmT2gI9zkgwl9h701dHMVEUDozkFKo4sQSTA5SwfzY0+bghF5o7AsCrXUBL/tdS3VKQR42cau8ESgA4LIMbaY3e96m7e01gSwSe8b9xDomsv8yuYWqSW2uZ0N8t4GF0QSJI7NBRkBbgpmuoB0nKxN/oxE8NR2gk88wMMRAgU4wKBgQDyyVgKJzQ4RHxLZXvIceeR0q0dfWi0bVx9KmYWgyzW8drXmbMeb1atoqk4Ly/jouTCSYchGBKYDHujSsnio8oz8w4Jwj1In4m0VIsU+zMld7yX8Uvu1E15nij+uUbPh03O4D0sRcJuWgbWnWsMZgY7tjayGOFp7mCbcEG7NE6QWwKBgCSVaiAEhfKUA6aAo+GQZksAfd2cOzcgEwswshhm5d34Ao5/MkJVAcPzey9gioZIor/wZNIgc+8aRYtYn7TMo4NDSjq9SlrSdGq5Q/9sMbrIv/WQCm0Hwkoxz8BobxosJV293XE9mUVM+K9L7qs5gH2Z+ry1cLRDs1nvAiEGyE+VAoGAZ8xjInweXEwTY9ywbkMcgQC0WJ5MTI9Q8oZU/Rz556+hI3on1UQ+p5+af1XVQJpc+R+ccS6sjGsR1P9djtL92PX6M3vi3ZCvu/RFPiQjespVTBSypRoJQYy39CdcOc+cGW1PWgU9GhbNQ6YrpTJdSdweSEhQ3ww2K150C8hSKm8CgYEAooGIgxJBo0MqH4JdCZpRJZ0btfD2TFq8qOTzPj/yKw+M1eir8tmksmj2mVNFMZNASXWIGZE+Fozr6WZMCBlg+SucwUZNrIqhOjl1wOGNSyvKsQlg5J7+EtWn+K+H/PYhDUesAgRZNGmyLb5nauY5XrqvV6AJaSc2xKMeL0cFfi4=


logging:
  pattern:
    console: "%d - %msg%n"
  level:
    root: info



server:
  port: 8889
spring:
  redis:
    password: zhixun_MKoIjN!
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB