alipay:
  appid: 2016101600697642
  gateway: https://openapi.alipaydev.com/gateway.do
  publicKey:  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAn+e4XvV7jki+qTsL9YcoVQIVkopK9vmyJRuMhKFAsb0Y0Ta+Ioy2bzFU6Gh+T/w6/r3vLbKhmCex/Y+K1H1+p86uaO1iA3rszNeM9Ezpq4qKWJDwGZ1QOxRhBAazWE3SVe25CertVEddLFkATBtuZMPWMh5dmwHnHG49YSCcmPSENIhaGRYj3bDXXHfIjlgUEsvB/z2DgjzY7JrbA2S62LRwPTIxhhkT8F92IEq1BD5gMsswAA2ipPQhCio9Q0Jw4QO9+bpIm7gQ5FgDLCSAjRBYfJdSpD6oLCRz1qfeg3OLOdYCQpOb/TsPbU8AbbIrrYg4z4wvzKC0LC+XBJmvawIDAQAB
  privateKey: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCMUou7WssrlY3clYHp1SIt7rRm+RrpJ8ioa2UtS0hOXD5oWI9yiJmumYrn/X2QJ0Zz0qknNjxPk9pelEN6SiTCS1RrvBqEi13lQM2bpOoDU4TM1V4F9FQUN0RBHOwXik2jcstLvOVMT5QPIEuVhfrW/HVz5nlkFLvtV1KOnNcJ/uRvhv6VAx6itXvUNyjtDRcFq07MyXNjAUOhabpS4WPsSgpn/hoSD1UMCAcyIXeDDbjpEULAe9aCN0/djFVl8VbSkcJk0wyEREIcdU+aen9B2o0DVsJEZ48DbGkEVzgruHu+jqo3vj7tciOomMG2Kx3Bc1kVxDPaRmCS/eScO1RZAgMBAAECggEAGdSYJETyYXOGSbS71W+Gey4Vx17TtVe9eENMvKm/Ba21Tz/+J/c9Uwawq0PeeUrBjVCaEr3JHFz7Na3VPg2n9pwnTi2yM/PztN/Y+W3CJhqZt5sPU8lGMPJ7fgD09OBgqlXXVnnPO9zqRF6Ni1i+dBTFCjDC58lpTqdkaxwz+YLLJ8AlTL/InRFPGj7DFKL6pgs03C+IvBHILHPXo+Z0F/aPYemHF8/R0yW63U6DHpFFC6pWm5SgZkDeFcaf4MKQfnjB4suNkbO0fJGopmNtRP7RnrdTL6HlutYNm7qa/RgrcXELy6bg2jFPBfGtE+cJrzbahAAdcqfDDMxlXCTqAQKBgQDmwaGlNSQE5WwFZkI2rWWmfBV9gpFq44/T26MUhBYT62tDc3Iugw7Ta3QoFxmR5J3TNcD3rOTEREcZ5kcZfYz6Ar44TrVgfez2ZoiPNIfsxOCnoL5s9rgw1cmEdynT+A8xsOOd/66HbQkamP2ULP/QNeDTWnHi5VGJEdJxJeIV/QKBgQCbrExJe5q+Ipf5PXNOL+hNtvT98zU2bTmqNTlRyAtQCXjDuEMSPFnvkdFeBcgOw1oXVfVAw+dIrJiFnNuFxFnPjGeQSsvW3ORn4pyDc/ODXtd2wMrht9kD70DuXBycvRnUX+g4bU9IHZA5dXK1588BBRwpfaRzMJoRd1XYdXOYjQKBgQDMZ7dNhb4rTCKcwdFjZ8PEbuQGctNncL6l90gFU1/PM1mnvSrmwpcudl/FZ3jyACZBwrr1akSXCrhE2/QdQ1bO3AEuFaKbH9D5DyhmWi0RcfBi7IPiN8Y/FBFW8suthW3IIZ3vBl7Ofapz0hPF3vqXsDJAZjy9tU69cXkNW3Zi7QKBgQCW2eDW+FscUoN4N48LvirbXCaOC+aNxkwx3v+be0FTHsqSxnTgL/Fq0J/U/788ZxtfL6HIT85Iw0/NchHbz0jEcadN0N00abs/2/2U+ICJ1hbu8aXoEvLN+EOwdzwWurxT61gpjetc06EVvPUaxvX2ZBBFOIZqRTeXI0/hwPbyZQKBgQDNQZftlIPVneUtYuZdnZ28W1ut1jvSLi9uldd776keHn313esRq+fPs6/4O0+G4Nq7MGTvNUCOeOFACv1XkmHReISpe/KUGO2/j0k9MjEtOEs6BB0fHsojLT6VrGmiqMynCLijWM1bLquJm6vJF/3EsavQlKZcpstEAMCLgrwTlg==


logging:
  pattern:
    console: "%d - %msg%n"
  level:
    root: info

server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB