// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package com;

public final class AddressBookProtos {
  private AddressBookProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Person)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 id = 2;</code>
     */
    int getId();

    /**
     * <code>string email = 3;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 3;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>.Person.PhoneNumber phones = 4;</code>
     */
    boolean hasPhones();
    /**
     * <code>.Person.PhoneNumber phones = 4;</code>
     */
    com.AddressBookProtos.Person.PhoneNumber getPhones();
    /**
     * <code>.Person.PhoneNumber phones = 4;</code>
     */
    com.AddressBookProtos.Person.PhoneNumberOrBuilder getPhonesOrBuilder();

    /**
     * <pre>
     *以最后一次设置的值为准，如果最后一次设置的值为math，那么Profession的值就是math
     * </pre>
     *
     * <code>string math = 11;</code>
     */
    java.lang.String getMath();
    /**
     * <pre>
     *以最后一次设置的值为准，如果最后一次设置的值为math，那么Profession的值就是math
     * </pre>
     *
     * <code>string math = 11;</code>
     */
    com.google.protobuf.ByteString
        getMathBytes();

    /**
     * <pre>
     *如果最后一次设置的值为compute，那么Profession的值就是compute
     * </pre>
     *
     * <code>string compute = 12;</code>
     */
    java.lang.String getCompute();
    /**
     * <pre>
     *如果最后一次设置的值为compute，那么Profession的值就是compute
     * </pre>
     *
     * <code>string compute = 12;</code>
     */
    com.google.protobuf.ByteString
        getComputeBytes();

    /**
     * <code>string chemistry = 13;</code>
     */
    java.lang.String getChemistry();
    /**
     * <code>string chemistry = 13;</code>
     */
    com.google.protobuf.ByteString
        getChemistryBytes();

    public com.AddressBookProtos.Person.ProfessionCase getProfessionCase();
  }
  /**
   * Protobuf type {@code Person}
   */
  public  static final class Person extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Person)
      PersonOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Person() {
      name_ = "";
      email_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {

              id_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              email_ = s;
              break;
            }
            case 34: {
              com.AddressBookProtos.Person.PhoneNumber.Builder subBuilder = null;
              if (phones_ != null) {
                subBuilder = phones_.toBuilder();
              }
              phones_ = input.readMessage(com.AddressBookProtos.Person.PhoneNumber.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(phones_);
                phones_ = subBuilder.buildPartial();
              }

              break;
            }
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();
              professionCase_ = 11;
              profession_ = s;
              break;
            }
            case 98: {
              java.lang.String s = input.readStringRequireUtf8();
              professionCase_ = 12;
              profession_ = s;
              break;
            }
            case 106: {
              java.lang.String s = input.readStringRequireUtf8();
              professionCase_ = 13;
              profession_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.AddressBookProtos.internal_static_Person_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.AddressBookProtos.internal_static_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.AddressBookProtos.Person.class, com.AddressBookProtos.Person.Builder.class);
    }

    /**
     * Protobuf enum {@code Person.PhoneType}
     */
    public enum PhoneType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>MOBILE = 0;</code>
       */
      MOBILE(0),
      /**
       * <code>HOME = 1;</code>
       */
      HOME(1),
      /**
       * <code>WORK = 2;</code>
       */
      WORK(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>MOBILE = 0;</code>
       */
      public static final int MOBILE_VALUE = 0;
      /**
       * <code>HOME = 1;</code>
       */
      public static final int HOME_VALUE = 1;
      /**
       * <code>WORK = 2;</code>
       */
      public static final int WORK_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static PhoneType valueOf(int value) {
        return forNumber(value);
      }

      public static PhoneType forNumber(int value) {
        switch (value) {
          case 0: return MOBILE;
          case 1: return HOME;
          case 2: return WORK;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          PhoneType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<PhoneType>() {
              public PhoneType findValueByNumber(int number) {
                return PhoneType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.AddressBookProtos.Person.getDescriptor().getEnumTypes().get(0);
      }

      private static final PhoneType[] VALUES = values();

      public static PhoneType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private PhoneType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Person.PhoneType)
    }

    public interface PhoneNumberOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Person.PhoneNumber)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>.Person.PhoneType number = 1;</code>
       */
      int getNumberValue();
      /**
       * <code>.Person.PhoneType number = 1;</code>
       */
      com.AddressBookProtos.Person.PhoneType getNumber();
    }
    /**
     * Protobuf type {@code Person.PhoneNumber}
     */
    public  static final class PhoneNumber extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:Person.PhoneNumber)
        PhoneNumberOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use PhoneNumber.newBuilder() to construct.
      private PhoneNumber(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private PhoneNumber() {
        number_ = 0;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private PhoneNumber(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                int rawValue = input.readEnum();

                number_ = rawValue;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.AddressBookProtos.internal_static_Person_PhoneNumber_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.AddressBookProtos.internal_static_Person_PhoneNumber_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.AddressBookProtos.Person.PhoneNumber.class, com.AddressBookProtos.Person.PhoneNumber.Builder.class);
      }

      public static final int NUMBER_FIELD_NUMBER = 1;
      private int number_;
      /**
       * <code>.Person.PhoneType number = 1;</code>
       */
      public int getNumberValue() {
        return number_;
      }
      /**
       * <code>.Person.PhoneType number = 1;</code>
       */
      public com.AddressBookProtos.Person.PhoneType getNumber() {
        @SuppressWarnings("deprecation")
        com.AddressBookProtos.Person.PhoneType result = com.AddressBookProtos.Person.PhoneType.valueOf(number_);
        return result == null ? com.AddressBookProtos.Person.PhoneType.UNRECOGNIZED : result;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (number_ != com.AddressBookProtos.Person.PhoneType.MOBILE.getNumber()) {
          output.writeEnum(1, number_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (number_ != com.AddressBookProtos.Person.PhoneType.MOBILE.getNumber()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(1, number_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.AddressBookProtos.Person.PhoneNumber)) {
          return super.equals(obj);
        }
        com.AddressBookProtos.Person.PhoneNumber other = (com.AddressBookProtos.Person.PhoneNumber) obj;

        if (number_ != other.number_) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + NUMBER_FIELD_NUMBER;
        hash = (53 * hash) + number_;
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.AddressBookProtos.Person.PhoneNumber parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.AddressBookProtos.Person.PhoneNumber parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.AddressBookProtos.Person.PhoneNumber parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.AddressBookProtos.Person.PhoneNumber parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.AddressBookProtos.Person.PhoneNumber parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.AddressBookProtos.Person.PhoneNumber parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.AddressBookProtos.Person.PhoneNumber parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.AddressBookProtos.Person.PhoneNumber parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.AddressBookProtos.Person.PhoneNumber parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.AddressBookProtos.Person.PhoneNumber parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.AddressBookProtos.Person.PhoneNumber parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.AddressBookProtos.Person.PhoneNumber parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.AddressBookProtos.Person.PhoneNumber prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Person.PhoneNumber}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Person.PhoneNumber)
          com.AddressBookProtos.Person.PhoneNumberOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.AddressBookProtos.internal_static_Person_PhoneNumber_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.AddressBookProtos.internal_static_Person_PhoneNumber_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.AddressBookProtos.Person.PhoneNumber.class, com.AddressBookProtos.Person.PhoneNumber.Builder.class);
        }

        // Construct using com.AddressBookProtos.Person.PhoneNumber.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          number_ = 0;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.AddressBookProtos.internal_static_Person_PhoneNumber_descriptor;
        }

        @java.lang.Override
        public com.AddressBookProtos.Person.PhoneNumber getDefaultInstanceForType() {
          return com.AddressBookProtos.Person.PhoneNumber.getDefaultInstance();
        }

        @java.lang.Override
        public com.AddressBookProtos.Person.PhoneNumber build() {
          com.AddressBookProtos.Person.PhoneNumber result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.AddressBookProtos.Person.PhoneNumber buildPartial() {
          com.AddressBookProtos.Person.PhoneNumber result = new com.AddressBookProtos.Person.PhoneNumber(this);
          result.number_ = number_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.AddressBookProtos.Person.PhoneNumber) {
            return mergeFrom((com.AddressBookProtos.Person.PhoneNumber)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.AddressBookProtos.Person.PhoneNumber other) {
          if (other == com.AddressBookProtos.Person.PhoneNumber.getDefaultInstance()) return this;
          if (other.number_ != 0) {
            setNumberValue(other.getNumberValue());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.AddressBookProtos.Person.PhoneNumber parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.AddressBookProtos.Person.PhoneNumber) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private int number_ = 0;
        /**
         * <code>.Person.PhoneType number = 1;</code>
         */
        public int getNumberValue() {
          return number_;
        }
        /**
         * <code>.Person.PhoneType number = 1;</code>
         */
        public Builder setNumberValue(int value) {
          number_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>.Person.PhoneType number = 1;</code>
         */
        public com.AddressBookProtos.Person.PhoneType getNumber() {
          @SuppressWarnings("deprecation")
          com.AddressBookProtos.Person.PhoneType result = com.AddressBookProtos.Person.PhoneType.valueOf(number_);
          return result == null ? com.AddressBookProtos.Person.PhoneType.UNRECOGNIZED : result;
        }
        /**
         * <code>.Person.PhoneType number = 1;</code>
         */
        public Builder setNumber(com.AddressBookProtos.Person.PhoneType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          
          number_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>.Person.PhoneType number = 1;</code>
         */
        public Builder clearNumber() {
          
          number_ = 0;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:Person.PhoneNumber)
      }

      // @@protoc_insertion_point(class_scope:Person.PhoneNumber)
      private static final com.AddressBookProtos.Person.PhoneNumber DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.AddressBookProtos.Person.PhoneNumber();
      }

      public static com.AddressBookProtos.Person.PhoneNumber getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<PhoneNumber>
          PARSER = new com.google.protobuf.AbstractParser<PhoneNumber>() {
        @java.lang.Override
        public PhoneNumber parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new PhoneNumber(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<PhoneNumber> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<PhoneNumber> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.AddressBookProtos.Person.PhoneNumber getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int professionCase_ = 0;
    private java.lang.Object profession_;
    public enum ProfessionCase
        implements com.google.protobuf.Internal.EnumLite {
      MATH(11),
      COMPUTE(12),
      CHEMISTRY(13),
      PROFESSION_NOT_SET(0);
      private final int value;
      private ProfessionCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ProfessionCase valueOf(int value) {
        return forNumber(value);
      }

      public static ProfessionCase forNumber(int value) {
        switch (value) {
          case 11: return MATH;
          case 12: return COMPUTE;
          case 13: return CHEMISTRY;
          case 0: return PROFESSION_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public ProfessionCase
    getProfessionCase() {
      return ProfessionCase.forNumber(
          professionCase_);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>int32 id = 2;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int EMAIL_FIELD_NUMBER = 3;
    private volatile java.lang.Object email_;
    /**
     * <code>string email = 3;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHONES_FIELD_NUMBER = 4;
    private com.AddressBookProtos.Person.PhoneNumber phones_;
    /**
     * <code>.Person.PhoneNumber phones = 4;</code>
     */
    public boolean hasPhones() {
      return phones_ != null;
    }
    /**
     * <code>.Person.PhoneNumber phones = 4;</code>
     */
    public com.AddressBookProtos.Person.PhoneNumber getPhones() {
      return phones_ == null ? com.AddressBookProtos.Person.PhoneNumber.getDefaultInstance() : phones_;
    }
    /**
     * <code>.Person.PhoneNumber phones = 4;</code>
     */
    public com.AddressBookProtos.Person.PhoneNumberOrBuilder getPhonesOrBuilder() {
      return getPhones();
    }

    public static final int MATH_FIELD_NUMBER = 11;
    /**
     * <pre>
     *以最后一次设置的值为准，如果最后一次设置的值为math，那么Profession的值就是math
     * </pre>
     *
     * <code>string math = 11;</code>
     */
    public java.lang.String getMath() {
      java.lang.Object ref = "";
      if (professionCase_ == 11) {
        ref = profession_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (professionCase_ == 11) {
          profession_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *以最后一次设置的值为准，如果最后一次设置的值为math，那么Profession的值就是math
     * </pre>
     *
     * <code>string math = 11;</code>
     */
    public com.google.protobuf.ByteString
        getMathBytes() {
      java.lang.Object ref = "";
      if (professionCase_ == 11) {
        ref = profession_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (professionCase_ == 11) {
          profession_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMPUTE_FIELD_NUMBER = 12;
    /**
     * <pre>
     *如果最后一次设置的值为compute，那么Profession的值就是compute
     * </pre>
     *
     * <code>string compute = 12;</code>
     */
    public java.lang.String getCompute() {
      java.lang.Object ref = "";
      if (professionCase_ == 12) {
        ref = profession_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (professionCase_ == 12) {
          profession_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *如果最后一次设置的值为compute，那么Profession的值就是compute
     * </pre>
     *
     * <code>string compute = 12;</code>
     */
    public com.google.protobuf.ByteString
        getComputeBytes() {
      java.lang.Object ref = "";
      if (professionCase_ == 12) {
        ref = profession_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (professionCase_ == 12) {
          profession_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHEMISTRY_FIELD_NUMBER = 13;
    /**
     * <code>string chemistry = 13;</code>
     */
    public java.lang.String getChemistry() {
      java.lang.Object ref = "";
      if (professionCase_ == 13) {
        ref = profession_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (professionCase_ == 13) {
          profession_ = s;
        }
        return s;
      }
    }
    /**
     * <code>string chemistry = 13;</code>
     */
    public com.google.protobuf.ByteString
        getChemistryBytes() {
      java.lang.Object ref = "";
      if (professionCase_ == 13) {
        ref = profession_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (professionCase_ == 13) {
          profession_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (id_ != 0) {
        output.writeInt32(2, id_);
      }
      if (!getEmailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_);
      }
      if (phones_ != null) {
        output.writeMessage(4, getPhones());
      }
      if (professionCase_ == 11) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, profession_);
      }
      if (professionCase_ == 12) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, profession_);
      }
      if (professionCase_ == 13) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, profession_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      if (!getEmailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, email_);
      }
      if (phones_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getPhones());
      }
      if (professionCase_ == 11) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, profession_);
      }
      if (professionCase_ == 12) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, profession_);
      }
      if (professionCase_ == 13) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, profession_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.AddressBookProtos.Person)) {
        return super.equals(obj);
      }
      com.AddressBookProtos.Person other = (com.AddressBookProtos.Person) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (getId()
          != other.getId()) return false;
      if (!getEmail()
          .equals(other.getEmail())) return false;
      if (hasPhones() != other.hasPhones()) return false;
      if (hasPhones()) {
        if (!getPhones()
            .equals(other.getPhones())) return false;
      }
      if (!getProfessionCase().equals(other.getProfessionCase())) return false;
      switch (professionCase_) {
        case 11:
          if (!getMath()
              .equals(other.getMath())) return false;
          break;
        case 12:
          if (!getCompute()
              .equals(other.getCompute())) return false;
          break;
        case 13:
          if (!getChemistry()
              .equals(other.getChemistry())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      if (hasPhones()) {
        hash = (37 * hash) + PHONES_FIELD_NUMBER;
        hash = (53 * hash) + getPhones().hashCode();
      }
      switch (professionCase_) {
        case 11:
          hash = (37 * hash) + MATH_FIELD_NUMBER;
          hash = (53 * hash) + getMath().hashCode();
          break;
        case 12:
          hash = (37 * hash) + COMPUTE_FIELD_NUMBER;
          hash = (53 * hash) + getCompute().hashCode();
          break;
        case 13:
          hash = (37 * hash) + CHEMISTRY_FIELD_NUMBER;
          hash = (53 * hash) + getChemistry().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.AddressBookProtos.Person parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.AddressBookProtos.Person parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.AddressBookProtos.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.AddressBookProtos.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.AddressBookProtos.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.AddressBookProtos.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.AddressBookProtos.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.AddressBookProtos.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.AddressBookProtos.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.AddressBookProtos.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.AddressBookProtos.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.AddressBookProtos.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.AddressBookProtos.Person prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Person)
        com.AddressBookProtos.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.AddressBookProtos.internal_static_Person_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.AddressBookProtos.internal_static_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.AddressBookProtos.Person.class, com.AddressBookProtos.Person.Builder.class);
      }

      // Construct using com.AddressBookProtos.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        id_ = 0;

        email_ = "";

        if (phonesBuilder_ == null) {
          phones_ = null;
        } else {
          phones_ = null;
          phonesBuilder_ = null;
        }
        professionCase_ = 0;
        profession_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.AddressBookProtos.internal_static_Person_descriptor;
      }

      @java.lang.Override
      public com.AddressBookProtos.Person getDefaultInstanceForType() {
        return com.AddressBookProtos.Person.getDefaultInstance();
      }

      @java.lang.Override
      public com.AddressBookProtos.Person build() {
        com.AddressBookProtos.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.AddressBookProtos.Person buildPartial() {
        com.AddressBookProtos.Person result = new com.AddressBookProtos.Person(this);
        result.name_ = name_;
        result.id_ = id_;
        result.email_ = email_;
        if (phonesBuilder_ == null) {
          result.phones_ = phones_;
        } else {
          result.phones_ = phonesBuilder_.build();
        }
        if (professionCase_ == 11) {
          result.profession_ = profession_;
        }
        if (professionCase_ == 12) {
          result.profession_ = profession_;
        }
        if (professionCase_ == 13) {
          result.profession_ = profession_;
        }
        result.professionCase_ = professionCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.AddressBookProtos.Person) {
          return mergeFrom((com.AddressBookProtos.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.AddressBookProtos.Person other) {
        if (other == com.AddressBookProtos.Person.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          onChanged();
        }
        if (other.hasPhones()) {
          mergePhones(other.getPhones());
        }
        switch (other.getProfessionCase()) {
          case MATH: {
            professionCase_ = 11;
            profession_ = other.profession_;
            onChanged();
            break;
          }
          case COMPUTE: {
            professionCase_ = 12;
            profession_ = other.profession_;
            onChanged();
            break;
          }
          case CHEMISTRY: {
            professionCase_ = 13;
            profession_ = other.profession_;
            onChanged();
            break;
          }
          case PROFESSION_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.AddressBookProtos.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.AddressBookProtos.Person) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int professionCase_ = 0;
      private java.lang.Object profession_;
      public ProfessionCase
          getProfessionCase() {
        return ProfessionCase.forNumber(
            professionCase_);
      }

      public Builder clearProfession() {
        professionCase_ = 0;
        profession_ = null;
        onChanged();
        return this;
      }


      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 2;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 2;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 2;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 3;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 3;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       */
      public Builder clearEmail() {
        
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        email_ = value;
        onChanged();
        return this;
      }

      private com.AddressBookProtos.Person.PhoneNumber phones_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.AddressBookProtos.Person.PhoneNumber, com.AddressBookProtos.Person.PhoneNumber.Builder, com.AddressBookProtos.Person.PhoneNumberOrBuilder> phonesBuilder_;
      /**
       * <code>.Person.PhoneNumber phones = 4;</code>
       */
      public boolean hasPhones() {
        return phonesBuilder_ != null || phones_ != null;
      }
      /**
       * <code>.Person.PhoneNumber phones = 4;</code>
       */
      public com.AddressBookProtos.Person.PhoneNumber getPhones() {
        if (phonesBuilder_ == null) {
          return phones_ == null ? com.AddressBookProtos.Person.PhoneNumber.getDefaultInstance() : phones_;
        } else {
          return phonesBuilder_.getMessage();
        }
      }
      /**
       * <code>.Person.PhoneNumber phones = 4;</code>
       */
      public Builder setPhones(com.AddressBookProtos.Person.PhoneNumber value) {
        if (phonesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          phones_ = value;
          onChanged();
        } else {
          phonesBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Person.PhoneNumber phones = 4;</code>
       */
      public Builder setPhones(
          com.AddressBookProtos.Person.PhoneNumber.Builder builderForValue) {
        if (phonesBuilder_ == null) {
          phones_ = builderForValue.build();
          onChanged();
        } else {
          phonesBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Person.PhoneNumber phones = 4;</code>
       */
      public Builder mergePhones(com.AddressBookProtos.Person.PhoneNumber value) {
        if (phonesBuilder_ == null) {
          if (phones_ != null) {
            phones_ =
              com.AddressBookProtos.Person.PhoneNumber.newBuilder(phones_).mergeFrom(value).buildPartial();
          } else {
            phones_ = value;
          }
          onChanged();
        } else {
          phonesBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Person.PhoneNumber phones = 4;</code>
       */
      public Builder clearPhones() {
        if (phonesBuilder_ == null) {
          phones_ = null;
          onChanged();
        } else {
          phones_ = null;
          phonesBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Person.PhoneNumber phones = 4;</code>
       */
      public com.AddressBookProtos.Person.PhoneNumber.Builder getPhonesBuilder() {
        
        onChanged();
        return getPhonesFieldBuilder().getBuilder();
      }
      /**
       * <code>.Person.PhoneNumber phones = 4;</code>
       */
      public com.AddressBookProtos.Person.PhoneNumberOrBuilder getPhonesOrBuilder() {
        if (phonesBuilder_ != null) {
          return phonesBuilder_.getMessageOrBuilder();
        } else {
          return phones_ == null ?
              com.AddressBookProtos.Person.PhoneNumber.getDefaultInstance() : phones_;
        }
      }
      /**
       * <code>.Person.PhoneNumber phones = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.AddressBookProtos.Person.PhoneNumber, com.AddressBookProtos.Person.PhoneNumber.Builder, com.AddressBookProtos.Person.PhoneNumberOrBuilder> 
          getPhonesFieldBuilder() {
        if (phonesBuilder_ == null) {
          phonesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.AddressBookProtos.Person.PhoneNumber, com.AddressBookProtos.Person.PhoneNumber.Builder, com.AddressBookProtos.Person.PhoneNumberOrBuilder>(
                  getPhones(),
                  getParentForChildren(),
                  isClean());
          phones_ = null;
        }
        return phonesBuilder_;
      }

      /**
       * <pre>
       *以最后一次设置的值为准，如果最后一次设置的值为math，那么Profession的值就是math
       * </pre>
       *
       * <code>string math = 11;</code>
       */
      public java.lang.String getMath() {
        java.lang.Object ref = "";
        if (professionCase_ == 11) {
          ref = profession_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (professionCase_ == 11) {
            profession_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *以最后一次设置的值为准，如果最后一次设置的值为math，那么Profession的值就是math
       * </pre>
       *
       * <code>string math = 11;</code>
       */
      public com.google.protobuf.ByteString
          getMathBytes() {
        java.lang.Object ref = "";
        if (professionCase_ == 11) {
          ref = profession_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (professionCase_ == 11) {
            profession_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *以最后一次设置的值为准，如果最后一次设置的值为math，那么Profession的值就是math
       * </pre>
       *
       * <code>string math = 11;</code>
       */
      public Builder setMath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  professionCase_ = 11;
        profession_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *以最后一次设置的值为准，如果最后一次设置的值为math，那么Profession的值就是math
       * </pre>
       *
       * <code>string math = 11;</code>
       */
      public Builder clearMath() {
        if (professionCase_ == 11) {
          professionCase_ = 0;
          profession_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       *以最后一次设置的值为准，如果最后一次设置的值为math，那么Profession的值就是math
       * </pre>
       *
       * <code>string math = 11;</code>
       */
      public Builder setMathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        professionCase_ = 11;
        profession_ = value;
        onChanged();
        return this;
      }

      /**
       * <pre>
       *如果最后一次设置的值为compute，那么Profession的值就是compute
       * </pre>
       *
       * <code>string compute = 12;</code>
       */
      public java.lang.String getCompute() {
        java.lang.Object ref = "";
        if (professionCase_ == 12) {
          ref = profession_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (professionCase_ == 12) {
            profession_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *如果最后一次设置的值为compute，那么Profession的值就是compute
       * </pre>
       *
       * <code>string compute = 12;</code>
       */
      public com.google.protobuf.ByteString
          getComputeBytes() {
        java.lang.Object ref = "";
        if (professionCase_ == 12) {
          ref = profession_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (professionCase_ == 12) {
            profession_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *如果最后一次设置的值为compute，那么Profession的值就是compute
       * </pre>
       *
       * <code>string compute = 12;</code>
       */
      public Builder setCompute(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  professionCase_ = 12;
        profession_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *如果最后一次设置的值为compute，那么Profession的值就是compute
       * </pre>
       *
       * <code>string compute = 12;</code>
       */
      public Builder clearCompute() {
        if (professionCase_ == 12) {
          professionCase_ = 0;
          profession_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       *如果最后一次设置的值为compute，那么Profession的值就是compute
       * </pre>
       *
       * <code>string compute = 12;</code>
       */
      public Builder setComputeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        professionCase_ = 12;
        profession_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string chemistry = 13;</code>
       */
      public java.lang.String getChemistry() {
        java.lang.Object ref = "";
        if (professionCase_ == 13) {
          ref = profession_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (professionCase_ == 13) {
            profession_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string chemistry = 13;</code>
       */
      public com.google.protobuf.ByteString
          getChemistryBytes() {
        java.lang.Object ref = "";
        if (professionCase_ == 13) {
          ref = profession_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (professionCase_ == 13) {
            profession_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string chemistry = 13;</code>
       */
      public Builder setChemistry(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  professionCase_ = 13;
        profession_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string chemistry = 13;</code>
       */
      public Builder clearChemistry() {
        if (professionCase_ == 13) {
          professionCase_ = 0;
          profession_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>string chemistry = 13;</code>
       */
      public Builder setChemistryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        professionCase_ = 13;
        profession_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Person)
    }

    // @@protoc_insertion_point(class_scope:Person)
    private static final com.AddressBookProtos.Person DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.AddressBookProtos.Person();
    }

    public static com.AddressBookProtos.Person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Person>
        PARSER = new com.google.protobuf.AbstractParser<Person>() {
      @java.lang.Override
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Person(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Person> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.AddressBookProtos.Person getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Person_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Person_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Person_PhoneNumber_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Person_PhoneNumber_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Person.proto\"\373\001\n\006Person\022\014\n\004name\030\001 \001(\t\022" +
      "\n\n\002id\030\002 \001(\005\022\r\n\005email\030\003 \001(\t\022#\n\006phones\030\004 \001" +
      "(\0132\023.Person.PhoneNumber\022\016\n\004math\030\013 \001(\tH\000\022" +
      "\021\n\007compute\030\014 \001(\tH\000\022\023\n\tchemistry\030\r \001(\tH\000\032" +
      "0\n\013PhoneNumber\022!\n\006number\030\001 \001(\0162\021.Person." +
      "PhoneType\"+\n\tPhoneType\022\n\n\006MOBILE\020\000\022\010\n\004HO" +
      "ME\020\001\022\010\n\004WORK\020\002B\014\n\nProfessionB\030\n\003comB\021Add" +
      "ressBookProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Person_descriptor,
        new java.lang.String[] { "Name", "Id", "Email", "Phones", "Math", "Compute", "Chemistry", "Profession", });
    internal_static_Person_PhoneNumber_descriptor =
      internal_static_Person_descriptor.getNestedTypes().get(0);
    internal_static_Person_PhoneNumber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Person_PhoneNumber_descriptor,
        new java.lang.String[] { "Number", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
