
mybatis:
  mapper-locations: classpath:com/mapper/*Mapper.xml
  type-aliases-package: com.pojo


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://127.0.0.1:8066/TESTDB?characterEncoding=utf8
        username: user
        password: user
      # 从库数据源
      slave:
        # 从数据源开关/默认关闭
        enabled: false
        url: jdbc:mysql://127.0.0.1:3306/pyg?useUnicode=true&characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true&serverTimezone=UTC&allowMultiQueries=true&allowPublicKeyRetrieval=true
        username: root
        password: root
